### ISSUE TITLE
getting an error its not working at all

### ISSUE THREAD

**Issue by ghost** [tightenco/laravel-mix-react#1]
Getting nothing but errors on this. I've tried requiring it and got 

"Error: Cannot find module 'laravel-mix-react'"

https://runkit.com/npm/laravel-mix-react

> @ dev /Users/joe/code/php/39dgv54
> node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix-react/setup/webpack.config.js

/Users/joe/code/php/39dgv54/node_modules/laravel-mix-react/setup/webpack.config.js:112
    Mix[Mix.cssPreprocessor].forEach(toCompile => {
                            ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.<anonymous> (/Users/joe/code/php/39dgv54/node_modules/laravel-mix-react/setup/webpack.config.js:112:29)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/joe/code/php/39dgv54/node_modules/webpack/bin/convert-argv.js:80:13)
    at Object.<anonymous> (/Users/joe/code/php/39dgv54/node_modules/webpack/bin/webpack.js:39:40)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)

**Comment by andree-bjorkgard** [comment]
@jaysg Looks like you had the same problem that I did... Made a pr that will fix it for laravel 5.4.
